## Copyright (c) 2022, Oracle and/or its affiliates. 
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy a .NET application to Microsoft Windows instances"
description: "Deploy a sample ASP .NET application in a highly available configuration, with two Windows instances and a load balancer."
schemaVersion: 1.1.0
version: "20190404"
locale: "en"

variableGroups:
- title: General Configuration
  visible: false
  variables:
  - tenancy_ocid
  - region
  - compartment_ocid

- title: Required Configuration
  visible: true  
  variables:
  - availablity_domain_name
  - instance_password
  - deploy_db_tier 
  - show_advanced

- title: Networking Configuration
  visible: 
      and:
        - show_advanced 
  variables:   
  - vcn_cidr
  - subnet1_cidr
  - subnet2_cidr

- title: Load Balancer Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - lb_shape
  - flex_lb_min_shape
  - flex_lb_max_shape

- title: Compute Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - instance_shape
  - shape_flex_ocpus
  - shape_flex_memory
  - instance_name

- title: MSSQL Configuration
  visible: 
      and:
        - show_advanced
  variables:
  - mssql_primary_shape
  - mssql_standby_shape

- title: Hidden Parameters
  visible: false
  variables:
  - userdata
  - cloudinit_ps1
  - cloudinit_config
  - index_html
  - image_os
  - image_os_version
  - is_winrm_configured_for_image
  - is_winrm_configured_for_ssl
  - release

outputGroups:
- title: Deployment Details
  outputs:
  - instance_public_ip1
  - instance_public_ip2
  - username1
  - username2
  - lb_public_ip

outputs:

  instance_public_ip1:
    type: link
    title: Instance 1
    description: Public IP for connecting to instance 1 over Remote Desktop
  
  instance_public_ip2:
    type: link
    title: Instance 2 Public IP
    description: Public IP for connecting to instance 2 over Remote Desktop
  
  username1:
    type: link
    title: Username (instance 1)
    description: User name login to instance 1
  
  username2:
    type: link
    title: Username (instance 2)
    description: Username to login to instance 2
  
  lb_public_ip:
    type: link
    title: Launch Application
    description: Open the ASP.NET application deployed to OCI

variables:

  show_advanced:
    type: boolean
    title: "Show advanced options?"
    description: "Shows advanced options."
    visible: true
    default: false

  instance_password:
    type: password
    required: true
    title: "Windows login password for user: opc"
    description: "Used to login to the instance over remote desktop. Password must at least 12 characters long and include at least one uppercase letter, one lowercase letter, and one numeric character"
    pattern: "^(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?=.*[!@#$%^&*()_+\\-=\\[\\]{};':\\\"\\\\|,.<>\\/?]).{12,32}$"
    visible: true
 
  compartment_ocid:
    type: oci:identity:compartment:id
    title: "Compartment"
    description: "The compartment in which to create Apex instance"
    required: true
  
  availablity_domain_name:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: true
    title: "Availability Domain to be chosen"
    description: "Availability Domain to be chosen"
    dependsOn:
      compartmentId: ${compartment_ocid}

  deploy_db_tier:
    type: boolean
    visibile: true
    default: true
    required: false
    title: "Deploy MS SQL Primary and Standby nodes"
    description: "Check the box to deploy MS SQL Primary and Standby nodes in private subnet."

  vcn_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "VCN CIDR Block"
    description: "Choose CIDR block for your VCN."
    default: "10.1.0.0/16"

  subnet1_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Public Subnet CIDR Block"
    description: "Choose CIDR block for your Subnet."
    default: "10.1.20.0/24"

  subnet2_cidr:
    type: string
    required: false
    pattern: "^(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9]).(25[0-5]|2[0-4][0-9]|1[0-9][0-9]|[1-9]?[0-9])\\/(3[0-2]|[1-2]?[0-9])$"
    title: "Private Subnet CIDR Block"
    description: "Choose CIDR block for your Subnet."
    default: "10.1.21.0/24"

  lb_shape:
    type: enum
    title: "Load Balancer Shape"
    description: "Load Balancer Shape"
    default: "flexible"
    required: false 
    enum:
      - "flexible"
      - "100Mbps"
      - "10Mbps"
      - "10Mbps-Micro"
      - "400Mbps"
      - "8000Mbps"

  flex_lb_min_shape:
    type: enum
    required: false
    default: "10"
    title: "LB Flex Min Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  flex_lb_max_shape:
    type: enum
    required: false
    default: "100"
    title: "LB Flex Max Shape"
    description: "Choose Minimum Shape for Flex Load Balancer."
    enum:
      - "10"
      - "100"
      - "1000"
      - "400"
      - "8000"
    visible:
      and:
        - eq:
          - lb_shape 
          - "flexible"

  instance_shape:
    type: oci:core:instanceshape:name
    required: false
    title: "Instance Shape"
    description: "The compute shape to use."
    default: "VM.Standard.E4.Flex"
    dependsOn:
      compartmentId: ${compartment_ocid}

  flex_shape_ocpus:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 1
    title: "Flex Shape OCPUs"
    description: "Choose number of OCPUs for Flex Shape."
    visible:
       and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - instance_shape
            - "VM.Optimized3.Flex"

  flex_shape_memory:
    type: number
    required: false
    minimum: 1
    maximum: 128
    multipleOf: 1
    default: 10
    title: "Flex Shape Memory (GB)"
    description: "Choose number GB for Flex Shape Memory."
    visible:
       and:
        - or:
          - eq:
            - instance_shape 
            - "VM.Standard.E3.Flex"
          - eq:
            - instance_shape 
            - "VM.Standard.E4.Flex"
          - eq:
            - instance_shape
            - "VM.Optimized3.Flex"
  
  instance_name:
    type: string
    required: false
    visible: false
    title: "Instance Name"
    description: "Name for the instance"

  mssql_primary_shape:
    type: enum
    required: false
    default: "VM.Standard2.2"
    title: "MSSQL Primary Shape"
    description: "Choose Shape for MSSQL Primary Database Server."
    enum:
      - "VM.Standard2.2"
      - "VM.Standard2.4"
      - "VM.Standard2.8"
      - "VM.Standard2.16"
      - "VM.Standard2.24"
      - "VM.DenseIO2.8"
      - "VM.DenseIO2.16"
      - "VM.DenseIO2.24"
      - "BM.Standard2.52"
    visible: 
      and:
        - deploy_db_tier

  mssql_standby_shape:
    type: enum
    required: false
    default: "VM.Standard2.2"
    title: "MSSQL Standby Shape"
    description: "Choose Shape for MSSQL Standby Database Server."
    enum:
      - "VM.Standard2.2"
      - "VM.Standard2.4"
      - "VM.Standard2.8"
      - "VM.Standard2.16"
      - "VM.Standard2.24"
      - "VM.DenseIO2.8"
      - "VM.DenseIO2.16"
      - "VM.DenseIO2.24"
      - "BM.Standard2.52"
    visible: 
      and:
        - deploy_db_tier

  userdata:
    type: string
    required: false
    visible: false
    title: "userdata directory"
    description: "Name of the userdata directory"
  
  cloudinit_ps1:
    type: string
    required: false
    visible: false
    title: "cloudinit_ps1 name"
    description: "Name of the cloudinit_ps1 script"
  
  cloudinit_config:
    type: string
    required: false
    visible: false
    title: "cloudinit_config name"
    description: "Name of the cloudinit_config file"
  
  index_html:
    type: string
    required: false
    visible: false
    title: "index_html file"
    description: "Name of the index_html file"
  
  image_os:
    type: string
    required: false
    visible: false
    title: "OS Image"
    description: "The OS image to use"
  
  image_os_version:
    type: string
    required: false
    visible: false
    title: "OS version"
    description: "Version of the image os"
  
  is_winrm_configured_for_image:
    type: boolean
    required: false
    visible: false
    title: "WinRM enabled Image ?"
    description: "WinRM support in image"
  
  is_winrm_configured_for_ssl:
    type: boolean
    required: false
    visible: false
    title: "Use SSL for WinRM ?"
    description: "Use SSL for WinRM"
